version: 2.1
executors:
  build_machine:
    machine:
      image: windows-server-2022-gui:current
    resource_class: windows.large
commands:
  setup:
    steps:
      - run:
          command: |
            choco install openjdk17 -y
          shell: powershell.exe
  startings:
    steps:
      - run:
          command: |
            java -jar testfile.jar
          shell: powershell.exe
jobs:
  st:
    executor: build_machine
    parameters:
      node:
        type: string
        default: "default"
    steps:
      - checkout
      - setup
      - startings
workflows:
  run:
    jobs:
      - st:
          matrix:
            parameters:
              node:
                - "alpha-fox"
                - "blue-nova"
                - "crimson-leaf"
                - "delta-storm"
                - "ember-wind"
                - "frozen-peak"
                - "golden-moon"
                - "hollow-tree"
                - "ice-shadow"
                - "jade-wave"
                - "kilo-spark"
                - "lunar-flame"
                - "midnight-sky"
                - "nova-blade"
                - "onyx-river"
                - "plasma-hawk"
                - "quantum-fog"
                - "red-mist"
                - "silver-wolf"
                - "terra-vibe"
                - "ultra-bloom"
                - "vortex-sand"
                - "wild-mango"
                - "xeno-bird"
                - "yellow-thorn"
                - "zenith-glow"
                - "ocean-breeze"
                - "neon-dust"
                - "storm-binder"
                - "radiant-echo"
